apiVersion: interview.com/v1alpha1
kind: Dummy
metadata:
  labels:
    app.kubernetes.io/name: dummy
    app.kubernetes.io/instance: dummy-sample
    app.kubernetes.io/part-of: dummy-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dummy-operator
  name: dummy-sample
  namespace: default
spec:
  # TODO(user): Add fields here
  message: "I'm just a dummy!"
